version: '3'
services: 
  database:
    container_name: mysql
    image: mysql/mysql-server:8.0.32
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scadalts
    expose: ["3306"]
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./db_conf:/etc/mysql:ro
    command: --log_bin_trust_function_creators=1
    network_mode: bridge

  scadalts:
    container_name: scadalts
    image: scadalts/scadalts:latest
    environment:
      - CATALINA_OPTS=-Xmx2G -Xms2G
    ports: 
      - "8080:8080"
    depends_on: 
      - database
    expose: ["8080", "8000"]
    volumes:
      - ./tomcat_log:/usr/local/tomcat/logs:rw
    links:
      - database:database
    command:
      - /usr/bin/wait-for-it
      - --host=database
      - --port=3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/tomcat/bin/catalina.sh
      - run
    network_mode: bridge
